#!/usr/bin/env python3
"""
glyph_daily_feed.py — Morning feed for Glyph event system.

Runs once per day. Scans local data sources, packages what it finds
into glyph_event_record JSON files, drops them into events/.

This script feeds Glyph. It does not reason. It does not decide.
It reads, measures, formats, and saves.

Data sources scanned:
  1. framework_kb.json   — new KB entries since last feed
  2. log_entries.json     — new log entries since last feed
  3. math_progress.json   — math session state

Each source that has new data produces one event record per run.
"""

import os, json, datetime
from collections import Counter

# --- Paths ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
EVENTS_DIR = os.path.join(BASE_DIR, "events")
FEED_STATE_FILE = os.path.join(BASE_DIR, "feed_state.json")

# Data files
KB_FILE = os.path.join(BASE_DIR, "framework_kb.json")
LOG_FILE = os.path.join(BASE_DIR, "log_entries.json")
MATH_FILE = os.path.join(BASE_DIR, "math_progress.json")

os.makedirs(EVENTS_DIR, exist_ok=True)


def load_json(path, default):
    if os.path.exists(path):
        try:
            with open(path) as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            return default
    return default


def save_json(path, data):
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def load_feed_state():
    """Track what was already fed so we only process new data."""
    return load_json(FEED_STATE_FILE, {
        "last_feed": None,
        "kb_count": 0,
        "log_count": 0,
        "math_attempts": 0
    })


def save_feed_state(state):
    save_json(FEED_STATE_FILE, state)


def next_event_id():
    """Count existing event files and return next sequential id."""
    existing = [f for f in os.listdir(EVENTS_DIR) if f.endswith(".json")]
    return len(existing) + 1


def make_event(num, domain, source_type, title, cycle_start, cycle_end,
               cycle_length, cycle_unit, event_name, event_def,
               event_position, event_unit, method_note="", route="memory"):
    """Build a complete glyph_event_record dict."""
    now = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    today = datetime.date.today().isoformat()
    rid = f"gev_{num:06d}"

    # Metrics
    if cycle_length > 0:
        ratio = event_position / cycle_length
    else:
        ratio = 0.0
    ref = 0.39
    band_min, band_max = 0.30, 0.49
    inside = band_min <= ratio <= band_max
    dist = abs(ratio - ref)

    # Status
    has_all = bool(cycle_start and cycle_end and event_def and event_position is not None)
    status = "live" if has_all else "draft"

    return {
        "record_id": rid,
        "source_id": f"feed_{today}_{domain}",
        "domain": domain,
        "source_type": source_type,
        "title": title,
        "cycle_definition": {
            "cycle_start": cycle_start,
            "cycle_end": cycle_end,
            "cycle_length": cycle_length,
            "cycle_unit": cycle_unit
        },
        "irreversible_event": {
            "event_name": event_name,
            "event_definition": event_def,
            "event_position": event_position,
            "event_unit": event_unit
        },
        "metrics": {
            "clustering_ratio": round(ratio, 6),
            "reference_point": ref,
            "convergence_band_min": band_min,
            "convergence_band_max": band_max,
            "inside_band": inside,
            "distance_from_reference": round(dist, 6)
        },
        "routing": {
            "route": route,
            "status": status
        },
        "snapshot": {
            "snapshot_time": now,
            "run_id": f"feed_{today}",
            "tick_id": f"tick_{num:06d}",
            "version": "v1"
        },
        "relations": {
            "parent_record_id": None,
            "linked_records": [],
            "linked_files": []
        },
        "notes": {
            "method_note": method_note,
            "confidence_note": "auto-generated by daily feed",
            "review_note": ""
        }
    }


def feed_framework_kb(state):
    """If KB has new entries since last feed, create an event."""
    kb = load_json(KB_FILE, [])
    prev_count = state.get("kb_count", 0)
    current_count = len(kb)

    if current_count <= prev_count:
        return None  # nothing new

    new_entries = kb[prev_count:]
    new_titles = [e.get("title", "untitled") for e in new_entries]
    delta = current_count - prev_count

    num = next_event_id()
    ev = make_event(
        num=num,
        domain="research",
        source_type="text",
        title=f"KB feed: {delta} new entries — {', '.join(new_titles[:3])}",
        cycle_start=new_entries[0].get("added", "unknown"),
        cycle_end=datetime.date.today().isoformat(),
        cycle_length=current_count,
        cycle_unit="entries",
        event_name="knowledge_addition",
        event_def="new framework KB entries recorded since last feed",
        event_position=current_count,
        event_unit="entries",
        method_note=f"delta={delta}, prev={prev_count}, now={current_count}",
        route="memory"
    )
    state["kb_count"] = current_count
    return ev


def feed_log_entries(state):
    """If log has new entries since last feed, create an event."""
    logs = load_json(LOG_FILE, [])
    prev_count = state.get("log_count", 0)
    current_count = len(logs)

    if current_count <= prev_count:
        return None

    new_logs = logs[prev_count:]
    delta = current_count - prev_count

    # Extract top keywords from new logs
    from collections import Counter
    import re
    stopwords = set("a an the is are was were be been have has had do does did will would could should i me my we you your he she it they them their and or but not so if of in on at to for with by from".split())
    words = []
    for entry in new_logs:
        tokens = re.findall(r'\b\w+\b', entry.get("text", "").lower())
        words.extend(t for t in tokens if t not in stopwords and len(t) > 2)
    top = [w for w, _ in Counter(words).most_common(5)]

    num = next_event_id()
    ev = make_event(
        num=num,
        domain="research",
        source_type="text",
        title=f"Log feed: {delta} new entries — keywords: {', '.join(top)}",
        cycle_start=new_logs[0].get("date", "unknown"),
        cycle_end=datetime.date.today().isoformat(),
        cycle_length=current_count,
        cycle_unit="entries",
        event_name="log_accumulation",
        event_def="new daily log entries recorded since last feed",
        event_position=current_count,
        event_unit="entries",
        method_note=f"delta={delta}, prev={prev_count}, now={current_count}",
        route="memory"
    )
    state["log_count"] = current_count
    return ev


def feed_math_progress(state):
    """If math has new attempts since last feed, create an event."""
    progress = load_json(MATH_FILE, {})
    total_attempts = sum(d.get("attempts", 0) for d in progress.values())
    total_correct = sum(d.get("correct", 0) for d in progress.values())
    prev_attempts = state.get("math_attempts", 0)

    if total_attempts <= prev_attempts:
        return None

    delta = total_attempts - prev_attempts

    num = next_event_id()
    ev = make_event(
        num=num,
        domain="math",
        source_type="dataset",
        title=f"Math feed: {delta} new attempts, {total_correct}/{total_attempts} correct",
        cycle_start="session_start",
        cycle_end=datetime.date.today().isoformat(),
        cycle_length=total_attempts,
        cycle_unit="trials",
        event_name="math_practice",
        event_def="new math practice attempts recorded since last feed",
        event_position=total_correct,
        event_unit="trials",
        method_note=f"delta={delta}, correct_rate={total_correct}/{total_attempts}",
        route="math"
    )
    state["math_attempts"] = total_attempts
    return ev


def run_daily_feed():
    """Main feed loop. Scan all sources, write events, update state."""
    today = datetime.date.today().isoformat()
    now = datetime.datetime.now().strftime("%H:%M:%S")
    print(f"  GLYPH DAILY FEED — {today} {now}")
    print(f"  Base: {BASE_DIR}")
    print(f"  Events: {EVENTS_DIR}")

    state = load_feed_state()
    last = state.get("last_feed", "never")
    print(f"  Last feed: {last}")
    print()

    created = 0

    # Feed each source
    feeders = [
        ("framework_kb", feed_framework_kb),
        ("log_entries", feed_log_entries),
        ("math_progress", feed_math_progress),
    ]

    for name, feeder in feeders:
        ev = feeder(state)
        if ev:
            rid = ev["record_id"]
            fpath = os.path.join(EVENTS_DIR, f"{rid}.json")
            save_json(fpath, ev)
            ratio = ev["metrics"]["clustering_ratio"]
            band = "YES" if ev["metrics"]["inside_band"] else "NO"
            print(f"  + {rid}  [{name}]  ratio={ratio:.4f}  band={band}")
            print(f"    {ev['title']}")
            created += 1
        else:
            print(f"  - {name}: no new data")

    # Update state
    state["last_feed"] = f"{today}T{now}"
    save_feed_state(state)

    print(f"\n  Feed complete. {created} new events created.")
    print(f"  State saved to feed_state.json\n")


if __name__ == "__main__":
    run_daily_feed()
